name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write   # for pushing version bump commit and tags
  id-token: write   # for npm provenance

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != '' }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Read package version
        id: pkg
        run: echo "version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: Create and push tag if missing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.pkg.outputs.version }}
          TAG=v${VERSION}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists locally"
          else
            git fetch --tags
          fi
          if git show-ref --tags --quiet --verify -- "refs/tags/$TAG"; then
            echo "Tag $TAG already exists on remote"
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Publish to npm
        if: ${{ env.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          npm publish --access public --provenance
