name: Release

on:
  push:
    tags:
      - 'v*.*.*'

# This workflow is triggered ONLY when a tag matching v*.*.* is pushed
# Tags are created by the "Tag on Version Bump" workflow after a version
# bump PR is merged to main
# This ensures releases happen only after version changes, not on every push

permissions:
  contents: write   # create GitHub Release notes
  id-token: write   # for npm provenance

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive tag from ref
        id: tag
        shell: bash
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Read package version
        id: pkg
        run: echo "version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - name: Verify tag matches package.json version
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "Tag: $TAG"
          PKG=v${{ steps.pkg.outputs.version }}
          echo "package.json: $PKG"
          if [ "$TAG" != "$PKG" ]; then
            echo "Tag ($TAG) does not match package.json version ($PKG)" >&2
            exit 1
          fi

      - name: Publish to npm
        if: ${{ env.NPM_TOKEN != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          npm publish --access public --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          generate_release_notes: true
